### ISSUE TITLE
Use a HashMap instead of Vec<(String, String)> for variables

### ISSUE THREAD

**Issue by A6GibKm** [charlesvdv/nom-bibtex#22]
I have a patch for this that I am using for [Citations](https://gitlab.gnome.org/World/citations), would you be interested in this?

**Comment by charlesvdv** [comment]
Honestly, I don't remember why I didn't use a HashMap instead of a Vec of tuples..

If this can avoid a potential fork, I guess I would prefer to have this integrated in the crate directly. It would also match a bit better with the semantic of a variable (only one value defined per variable). So, I would be open to the idea even if it mean a breaking change to the API.

**Comment by A6GibKm** [comment]
At this point I removed my use of a fork and just do
```
        let tags: HashMap<String, String> = bib
            .tags()
            .iter()
            .map(|(k, v)| (k.to_lowercase(), v.clone()))
            .collect();
```
doing the allocations is a bit unfortunate, but it is what it is. Ill try to post the patches during the week.
